server:
  sourceaddress: ""

database:
  sourcedbuser: "root"
  sourcedbpassword: "M@Tc#2024"

logger:
  logdirectory: "/Users/sahatsawat/Projects/MDMR/test/main/logs"
  logfilename: "app.log"

mdmr:
  sourceprefix: "admin_mtls_biz_"
  dumpthreads: 4
  stagingdirectory: "/Users/sahatsawat/Projects/MDMR/test/main/staging"
  repairstagingdirectory: "/Users/sahatsawat/Projects/MDMR/test/main/repair-staging"